Partyrole implemented
FIWARE/tmforum-api pull request #31
Opened 2023-10-05 16:13 UTC by sluFicodes

2023-10-16 07:38 UTC, wistefan requested changes

2023-10-16 07:38 UTC, wistefan commented on party-role/src/main/java/org/fiware/tmforum/partyrole/domain/AgreementRef.java
> +
Whats the reason to not use the AgreementRef from the commons module?

2023-10-16 07:38 UTC, wistefan commented on party-role/src/main/java/org/fiware/tmforum/partyrole/domain/AccountRef.java
> +
AccountRef, CreditProfile and PaymentMethodRef already exist as part of the customer-management module. It should be moved to  a shared module and reused

2023-10-16 07:38 UTC, wistefan commented on party-role/src/main/java/org/fiware/tmforum/partyrole/rest/PartyRoleController.java
> +                                                String.format("Was not able to create individual %s",
Exception Message should be updated.

2023-10-16 07:38 UTC, wistefan commented on party-role/src/main/java/org/fiware/tmforum/partyrole/rest/PartyRoleController.java
> +             Mono.error(new TmForumException("No such individual exists.", TmForumExceptionReason.NOT_FOUND)))
Exception Message should be updated.

2023-10-16 07:38 UTC, wistefan commented on party-role/src/main/java/org/fiware/tmforum/partyrole/rest/PartyRoleController.java
> +                throw new TmForumException("Did not receive a valid id, such agreement cannot exist.",
Exception Message should be updated.

2023-10-17 08:56 UTC, sluFicodes commented
Hi, all changes have been updated.

2023-10-18 08:06 UTC, wistefan commented
@sluFicodes Francisco mentioned that you need to run TMForum against Scorpio, however your tests fail with Scorpio. Can you please check? Just run "mvn clean test integration-test verify -Dbroker=scorpio" to test with it.

2023-11-03 08:53 UTC, beknazaresenbek requested changes

2023-11-03 08:53 UTC, beknazaresenbek commented on party-role/src/main/resources/application.yaml
> +  caches:
There were some changes in application properties. Now there are multiple properties for different environments. Could you adjust it? (As example, you can check account-module)

2023-11-03 08:53 UTC, beknazaresenbek commented on party-role/src/test/resources/application.yaml
> +  caches:
The same changes in application properties should be done for tests (check account-module, for example)

2023-11-03 08:53 UTC, beknazaresenbek commented on party-role/pom.xml
> +            <resource>
Could you put test resources in testResources tag? (check agreement-module, for example)

2023-12-11 10:54 UTC, sluFicodes commented
Okay it should be fine now

2023-12-19 07:26 UTC, beknazaresenbek approved these changes

2024-01-02 11:07 UTC, wistefan approved these changes

2024-01-02 11:10 UTC, merged